#!/usr/bin/env bash
# script that transfers a file from our client to a server
# takes 4 paramters
if [ $# -lt 3 ]; then
	echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

filepath="$1"
ip_address="$2"
username="$3"
ssh_key="$4"

scp -o StrictHostKeyChecking=no -i "filepath" "ssh_key" "username"@"ip_address":~
