#!/usr/bin/env bash
# a Bash script that configures a new Ubuntu machine that installs nginx
# and confugures nginx to listen at port 80

sudo apt-get update
sudo apr-get install nginx -y
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
# Configure nginx to listen on port 80
sudo sed -i 's/\blisten\s*80\b/listen 80;/g' /etc/nginx/sites-available/default
service nginx start
